version: "3.7"

services:

  strfry-relay:
    container_name: strfry-relay
    image: ghcr.io/hoytech/strfry:latest
    environment:
      VIRTUAL_HOST: relay.nostronline.online
      VIRTUAL_PORT: 7777
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: relay.nostronline.online
      LETSENCRYPT_EMAIL: admin@nostronline.online
    ports:
      - 7777:7777
    volumes:
      - ./my-strfry.conf:/etc/strfry.conf
      - ./my-strfry-db:/app/strfry-db
    #- ./write-policy.py:/app/write-policy.py
    networks:
      - proxy
      - nostr


  web:
    image: getumbrel/umbrel-nostr-relay
    user: "1000:1000"
    container_name: public-relay-web
    restart: on-failure
    environment:
      RELAY_HOST: "strfry-relay"
      RELAY_PORT: "7777"
    ports:
      - 3000:3000 # to access the web view use relay.nostrapp.online:3000
    networks:
      - proxy
      - nostr


networks:
  nostr:
    external: false
    name: nostr
  proxy:
    external: true
    name: proxy