services:
  strfry-nostr-relay:
    build:
      dockerfile: ./my-Dockerfile
    container_name: strfry
    restart: unless-stopped
    volumes:
      - ./my-strfry.conf:/etc/strfry.conf
      - ./my-strfry-db:/app/strfry-db
      - ./write-policy.py:/app/write-policy.py
    ports:
      - "7777:7777"
    logging:
      driver: syslog
  caddy:
    image: caddy:alpine
    container_name: strfry-caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data: